<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="MacBooks-MacBook-Pro.local" failures="1" tests="1" name="LoginTest" time="17.2" errors="0" timestamp="2022-01-22T17:24:27 GMT">
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="16.842">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at stepdefinitions.Login.verify_user_is_able_to_successfully_login(Login.java:57)
at âœ½.Verify user is able to successfully login(file:///Users/macbookpro/Documents/Selenium/FrameworkProj1/src/test/java/features/Login.feature:8)
]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- LoginTest -->
